### ISSUE TITLE
[REQUEST] Is this repo maintained?

### ISSUE THREAD

**Issue by kevando** [FrozenAtlas/OLC-Repo#5]
I'm no OLC never will be, but I'd like to help if I can. 

I found some stuff here helpful and could add some documentation to make it easier to find stuff if you'd think that's useful.

**Comment by emptyport** [comment]
It is maintained. We are starting to put together the wiki, so you can add stuff there or to the readme or wherever.

**Comment by kevando** [comment]
Duh. The wiki.

I never check the wiki on Github. Thanks!
